sudo: required

language: go

go:  
 - tip # The latest version of Go.

services:
  - docker

before_install:
- docker pull influxdb
- docker run -d -p 8086:8086 -v /var/lib/influxdb influxdb
- docker ps -a

script:
 - go test -v ./...
 - go build